apiVersion: apps/v1
kind: Deployment
metadata:
  name: hfjyk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hfjyk
  template:
    metadata:
      labels:
        app: hfjyk
    spec:
      containers:
      - image: okteto.dev/hfjyk:latest
        name: hfjyk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b01ef4cb-29cd-4d5f-a87b-53d271d5e640"
        - name: Vless_Path
          value: "/vlyr555"
        - name: Vmess_UUID
          value: "b01ef4cb-29cd-4d5f-a87b-53d271d5e640"
        - name: Vmess_Path
          value: "/vm6gh66"
        - name: Share_Path
          value: "/v2link"
